name: wanderingviolins
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: WanderingViolins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#787d8c'
    - '#612366'
    - '#bcb8c8'
    - '#e997e0'
    - '#e0e0eb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
