name: wanderingviolins
favicon: null
layout_spectrum: 0.7671376848593354
typography_spectrum: 0.6330062788911164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12182080280035734
  lightness: 0.4249145274516195
  saturation: 0.18784549832344055
  rhythmicContrast: 0.7944577431771904
purpose: []
