name: wanderingviolins
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: WanderingViolins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#bfc1ad'
    - '#b0000e'
    - '#a1844c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
