name: wanderingviolins
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: WanderingViolins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9d3512'
    - '#4c4c4c'
    - '#e9872d'
    - '#8e8a92'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
